routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as' => 'index',
    'uses' => 'IndexController@index',
]);;
Auth::routes();
Route::group(['middleware' => ['permission:worker']], function () {
    Route::resource('dashboard', 'DashBoardController');
    Route::get('/getpiedata/{id}', 'DashBoardController@getPie')->name('Data');
    Route::get('/getbardata/{id}', 'DashBoardController@getbar')->name('Data');
    Route::get('/activity', 'DashBoardController@activity')->name('Profile');
    Route::get('/workers/documents/{id}/edit', [
        'as' => 'workers.document.edit',
        'uses' => 'WorkerController@documents',
    ]);

    Route::post('/workers/permanent/delete/', [
        'as' => 'workers.delete.permanent',
        'uses' => 'WorkerController@deleteworker',
    ]);
    Route::post('/documents', [
        'as' => 'workers.document.updatedoc',
        'uses' => 'WorkerController@updatedoc',
    ]);
    Route::post('/workers/documents/download/', [
        'as' => 'workers.document.download',
        'uses' => 'WorkerDocsController@document_download',
    ]);
    Route::resource('workers', 'WorkerController');

});
Route::group(['middleware' => ['permission:administrator']], function () {
    Route::resource('client', 'ClientController');
    Route::post('client/delete', [
        'as' => 'client.delete',
        'uses' => 'ClientController@delete',
    ]);
    Route::post('client/state', [
        'as' => 'client.state',
        'uses' => 'ClientController@state',
    ]);
    Route::post('client/event/store', [
        'as' => 'client.store.event',
        'uses' => 'ClientController@storeEvent',
    ]);
    Route::get('client/{id}/create', [
        'as' => 'client.create.event',
        'uses' => 'ClientController@createEvent',
    ]);
    Route::get('client/event/{id}', [
        'as' => 'client.show.event',
        'uses' => 'ClientController@showEvent',
    ]);
    Route::post('client/event/delete', [
        'as' => 'client.delete.event',
        'uses' => 'ClientController@deleteEvent',
    ]);
    Route::post('client/event/state', [
        'as' => 'client.event.state',
        'uses' => 'ClientController@stateEvent',
    ]);
    Route::get('client/event/{id}/addworker/', [
        'as' => 'client.event.addWorker',
        'uses' => 'ClientController@addEventWorker',
    ]);

    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::get('/users/enterprise/new', [
        'as' => 'users.Enterprise',
        'uses' => 'UserController@Enterprise',
    ]);
    Route::get('/users/enterprise/change', [
        'as' => 'users.Enterprise.edit',
        'uses' => 'UserController@EnterpriseEdit',
    ]);
    Route::get('/admin/{id}/{date}/entfilter', [
        'as' => 'dashboard.company.filter',
        'uses' => 'AdminController@enterfilter',
    ]);
    Route::get('/admin/{id}/{date}/workfilter', [
        'as' => 'dashboard.worker.filter',
        'uses' => 'AdminController@workfilter',
    ]);

    Route::post('/users/enterprise', [
        'as' => 'users.store_enterprise',
        'uses' => 'UserController@PostEnterprise',
    ]);
    Route::post('/users/enterpriseedit', [
        'as' => 'users.store_enterprise_edit',
        'uses' => 'UserController@PostEnterpriseEdit',
    ]);
    Route::post('/admin-filter', [
        'as' => 'dashboard.filter',
        'uses' => 'AdminController@filter',
    ]);
    Route::resource('workers', 'WorkerController');
    Route::resource('admin', 'AdminController');
    Route::resource('otherworkers', 'OtherworkersController');
    Route::get('company/{id?}/details', [
        'as' => 'companies.info',
        'uses' => 'CompaniesController@details',
    ]);
    Route::post('company/details', [
        'as' => 'companies.info.update',
        'uses' => 'CompaniesController@detailsUpdate',
    ]);

    Route::resource('companies', 'CompaniesController');
    Route::get('company/{id?}/filter', [
        'as' => 'company.filter',
        'uses' => 'CompanyDocController@filter',
    ]);
    Route::post('/workers/documents/downloadadmin/', [
        'as' => 'workers.document.downloadadmin',
        'uses' => 'WorkerDocsController@document_download_admin',
    ]);
    Route::post('/company/delete', [
        'as' => 'company.delete',
        'uses' => 'CompanyDocController@deleteType',
    ]);
    Route::post('/company/create', [
        'as' => 'company.document.typecreate',
        'uses' => 'CompanyDocController@POST_type',
    ]);
    Route::get('/company/delete', [
        'as' => 'company.deleteview',
        'uses' => 'CompanyDocController@deleteview',
    ]);
    Route::post('/workers/type/delete', [
        'as' => 'workers.delete',
        'uses' => 'WorkerDocsController@deleteType',
    ]);
    Route::get('/workers/type/delete', [
        'as' => 'workers.deleteview',
        'uses' => 'WorkerDocsController@deleteview',
    ]);
    Route::get('/workers/documents/new', [
        'as' => 'workers.document.type',
        'uses' => 'WorkerController@newDocType',
    ]);
    Route::post('/documents/typecreate', [
        'as' => 'workers.document.POST_type',
        'uses' => 'WorkerController@POST_type',
    ]);
    Route::post('/worker/approve', [
        'as' => 'worker.document.approve',
        'uses' => 'WorkerDocsController@approve',
    ]);
    Route::post('/worker/deny', [
        'as' => 'worker.document.deny',
        'uses' => 'WorkerDocsController@deny',
    ]);
    Route::post('/worker/delete', [
        'as' => 'worker.document.delete',
        'uses' => 'WorkerDocsController@deletedoc',
    ]);
    Route::post('/company/approve', [
        'as' => 'company.document.approve',
        'uses' => 'CompanyDocController@approve',
    ]);
    Route::post('/company/deny', [
        'as' => 'company.document.deny',
        'uses' => 'CompanyDocController@deny',
    ]);
});
Route::group(['middleware' => ['permission:manager']], function () {
    Route::resource('company', 'CompanyDocController');
    Route::post('/company/getfile', [
        'as' => 'company.document.get',
        'uses' => 'CompanyDocController@POST_getFiles',
    ]);
    Route::post('/company/uploadfile', [
        'as' => 'company.document.set',
        'uses' => 'CompanyDocController@POST_upload',
    ]);
    Route::post('/event/file/download', [
        'as' => 'event.document.download',
        'uses' => 'ClientController@getDownload',
    ]);
    Route::post('/company/getDocs', [
        'as' => 'worker.document.get',
        'uses' => 'WorkerDocsController@getWorkerDocs',
    ]);
    Route::post('/client/event/worker/add', [
        'as' => 'client.event.store.worker',
        'uses' => 'ClientController@storeEventWorker',
    ]);
    Route::get('/Companyfileupload', [
        'as' => 'company.document.upload',
        'uses' => 'CompanyDocController@upload',
    ]);
    Route::get('/client/event/{id}/worker/{workerID}', [
        'as' => 'client.event.worker.show',
        'uses' => 'ClientController@showWorkerDocs',
    ]);
    Route::get('company/{id?}/filter', [
        'as' => 'company.filter',
        'uses' => 'CompanyDocController@filter',
    ]);
    Route::get('workers/{id?}/filter', [
        'as' => 'workers.filter',
        'uses' => 'WorkerDocsController@filter',
    ]);

    Route::resource('workers', 'WorkerController');

});
Route::group(['middleware' => ['permission:client']], function () {
    Route::resource('clientevents', 'ClientEventsController');
    Route::get('clientevents/{id}/{workerID}', [
        'as' => 'clientevents.worker',
        'uses' => 'ClientEventsController@worker',
    ]);
    Route::post('clientevents/filedownload', [
        'as' => 'clientevents.download',
        'uses' => 'ClientController@getDownload',
    ]);
});

resources/views/clientdashboard.blade.php
@extends('layouts.app')
@section('css')
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href="https://cdn.datatables.net/responsive/2.2.2/css/responsive.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href=" https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href="{{asset('custom/jquery-ui-1.12.1.custom/jquery-ui.css')}}"/>
	<link rel="stylesheet" type="text/css"
	      href="{{asset('css/tables-custom.css')}}"/>
@endsection
@section('main')
	<style>
		.border300 {
			border-radius: 300px;
		!important;
			padding: 0;
		!important;
			margin: 0 0 0;
		!important;

		}

		.fa25 {
			font-size: 25px;
		!important;
		}
	</style>
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="pull-left">
				<h2>Dashboard</h2>
			</div>
		</div>
	</div>


	@if ($message = Session::get('success'))
		<div class="alert alert-success">
			<p>{{ $message }}</p>
		</div>
	@endif
	@if ($message = Session::get('error'))
		<div class="alert alert-danger">
			<p>{{ $message }}</p>
		</div>
	@endif

	<div class="div-bg-gray ">
		<div class="card-body">
			<table id="key-table" style="width: 100%;" class="table table-striped table-hover dataTable border-table">
				<thead>
				<th>ENTIDADE</th>
				<th>DOCUMENTOS DA ENTIDADE</th>
				<th>DOCUMENTOS DOS COLABORADORES</th>
				</thead>
				<tbody>
				@foreach($data as $company)
					<tr>
						<td>
							<button class="btn"
							        onclick="showModal({{$company->enterpriseID}})">{{$company->enterpriseName}}</button>

							<div id="{{$company->enterpriseID}}" name="{{$company->enterpriseID}}"
							     class="modal fade bd-example-modal-lg"
							     tabindex="-1"
							     role="dialog"
							     aria-labelledby="myLargeModalLabel" aria-hidden="true">
								<div class="modal-dialog modal-lg">
									<div class="modal-content">
										<div class="modal-header text-black-50">{{$company->enterpriseName}}</div>
										<div class="pull-right mgr-25">
											<button class="btn btn-success
										pull-right" onclick="btntoogle({{$company->enterpriseID}})">Editar
											</button>
										</div>
										<div class="card">

											<div class="card-body">
												<div class="row">
													<form method="POST" action="{{route('companies.info.update')}}"
													      id="{{$company->enterpriseID}}{{$company
													->enterpriseName}}"
													      name="id="{{$company->enterpriseID}}{{$company->enterpriseName}}
													""
													class="mgl-25 mgr-25 width-100">
													@csrf
													<div class="form-group">
														<label for="id">Identificador:</label>
														<input type="id" name="id" class="form-control" id="id"
														       placeholder="{{$company->enterpriseID}}"
														       value="{{$company->enterpriseID}}"
														       disabled>
													</div>
													<div class="form-group">
														<label for="name">Nome:</label>
														<input type="text" name="name" class="form-control"
														       id="name"
														       placeholder="{{$company->enterpriseName}}"
														       value="{{$company->enterpriseName}}"
														       disabled>
													</div>
													<div class="form-group">
														<label for="name">Nif:</label>
														<input type="text" name="nif" class="form-control"
														       id="nif"
														       placeholder="{{$company->enterpriseNif}}"
														       value="{{$company->enterpriseNif}}"
														       disabled>
													</div>
													<div class="form-group">
														<label for="name">Morada:</label>
														<input type="text" name="address" class="form-control"
														       id="address"
														       placeholder="{{$company->enterpriseAddress}}"
														       value="{{$company->enterpriseAddress}}"
														       disabled>
													</div>
													<div id="btndiv{{$company->enterpriseID}}" style="display: none;">
														<button onclick="submit({{$company->enterpriseID}}{{$company->enterpriseName}}
																)" class="btn">Submit
														</button>
													</div>
													</form>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
		</div>
		</td>
		<td>
			@php
				$docs = \App\CompanyDocs::all()->where('company_id','=',$company->enterpriseID);
				$count_pend = $docs->where('valid','=','0')->count();
				$count_den = $docs->where('valid','=','2')->count();
				$count_app = $docs->where('valid','=','1')->count();
				$count_exp = $docs->where('expires_at','<',\Carbon\Carbon::today('Europe/Lisbon'))->where('valid','=','1')->count();
				if($count_den >0 or $count_exp > 0){
				echo'<a class="border300 btn btn-danger "
				href="'.route("company.filter",$company->enterpriseID).'"><i
				   class="fa25 fas fa-times-circle 1"></i></a>';
				}else if($count_pend >0){
				echo'<a class="border300 btn btn-warning " s
				href="'.route("company.filter",$company->enterpriseID).'"><i class="fa25 fas fa-exclamation-circle fa-1x"></i></a>';
				}else if($count_app >0){
				echo'<a class="border300 btn btn-success "
				href="'.route("company.filter",$company->enterpriseID).'"><i
				   class="fa25 fas fa-check fa-1x"></i></a>';
				}else{
				echo'<a class="border300 btn btn-info "
				href="'.route("company.filter",$company->enterpriseID).'">
				<i class="fa25 fas fa-plus-circle"></i></a>';

				//echo('<label class="badge badge-warning pd5-all text-16"><i class="fas fa-file-upload fa-2x"></i></label>');
				}
			@endphp
		</td>

		<td>
			@php
				$docs = \App\WorkerDocs::all()->where('company_id','=',$company->enterpriseID);
				$count_pend = $docs->where('valid','=','0')->count();
				$count_den = $docs->where('valid','=','2')->count();
				$count_app = $docs->where('valid','=','1')->count();
				$count_exp = $docs->where('expires_at','<',\Carbon\Carbon::today('Europe/Lisbon'))->where('valid','=','1')->count();

		if($count_den >0 or $count_exp > 0){
				echo'<a class="border300 btn btn-danger "
				href="'.route("workers.filter",$company->enterpriseID).'"><i
				   class="fa25 fas fa-times-circle 1"></i></a>';
				}else if($count_pend >0){
				echo'<a class="border300 btn btn-warning " s
				href="'.route("workers.filter",$company->enterpriseID).'"><i class="fa25 fas fa-exclamation-circle fa-1x"></i></a>';
				}else if($count_app >0){
				echo'<a class="border300 btn btn-success "
				href="'.route("workers.filter",$company->enterpriseID).'"><i
				   class="fa25 fas fa-check fa-1x"></i></a>';
				}else{
				echo'<a class="border300 btn btn-info "
				href="'.route("workers.filter",$company->enterpriseID).'">
				<i class="fa25 fas fa-plus-circle"></i></a>';

				//echo('<label class="badge badge-warning pd5-all text-16"><i class="fas fa-file-upload fa-2x"></i></label>');
				}
			@endphp
		</td>


		</tr>
		@endforeach
		</tbody>
		</table>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="pull-left">
					<h4>Legenda</h4>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3">
				<div>
					<strong>
						<a class="border300 btn btn-success"><i class="fa25 fas fa-check fa-1x"></i></a>&nbsp;Válido
					</strong>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3">
				<div>
					<strong>
						<a class="border300 btn btn-warning"><i class="fa25 fas
							fa-exclamation-circle"></i></a>&nbsp;Pendente
					</strong>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3">
				<div>
					<strong>
						<a class="border300 btn btn-danger"><i class="fa25 fas fa-times-circle"></i></a>&nbsp;Inválido
					</strong>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3">
				<div>
					<strong>
						<a class="border300 btn btn-info"><i class="fa25 fas fa-plus-circle"></i></a>&nbsp;Vazio
					</strong>
				</div>
			</div>
		</div>
	</div>
	</div>




@endsection
@section('script')

	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
	<script type="text/javascript"
	        src="https://cdn.datatables.net/responsive/2.2.2/js/dataTables.responsive.min.js"></script>
	<script type="text/javascript"
	        src="https://cdn.datatables.net/responsive/2.2.2/js/responsive.bootstrap4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.js"></script>
	<script src="{{asset('custom/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}"></script>
	<script>
        $(document).ready(function () {
            $('#key-table').DataTable({
                responsive: true, bInfo: false, bLengthChange: false,
                order: [0, 'desc'],
                "language": {
                    "sEmptyTable": "Nenhum registo encontrado",
                    "sProcessing": "A processar...",
                    "sLengthMenu": "Mostrar _MENU_ registos",
                    "sZeroRecords": "Não foram encontrados resultados",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registos",
                    "sInfoEmpty": "Mostrando de 0 até 0 de 0 registos",
                    "sInfoFiltered": "(filtrado de _MAX_ registos no total)",
                    "sInfoPostFix": "",
                    "sSearch": "Procurar:",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "Primeiro",
                        "sPrevious": "Anterior",
                        "sNext": "Seguinte",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }


                }
            });
        });
        $(function () {
            $("#datepicker").datepicker({
                dateFormat: 'yy-mm-dd',
                changeMonth: true,
                changeYear: true
            });
        });
	</script>

	<script>

        function showModal(id) {
            const inputs = document.getElementsByTagName('input');
            for (let i = 0; i < inputs.length; i++) {
                inputs[i].disabled = true;
            }
            $('#' + id).modal('show');

        }

        function btntoogle(id) {
            const inputs = document.getElementsByTagName('input');

            const x = document.getElementById("btndiv" + id);
            if (x.style.display === "none") {
                x.style.display = "block";
                for (let i = 1; i < inputs.length; i++) {
                    inputs[i].disabled = false;
                }

                $("input", "#key-table_filter").removeAttr('disabled');
            } else {
                x.style.display = "none";
                for (let i = 0; i < inputs.length; i++) {
                    inputs[i].disabled = true;
                }

                $("input", "#key-table_filter").removeAttr('disabled');
            }
        }

        function submit(id) {
            $("#" + id).submit();
        }

	</script>

@endsection

resources/views/clientevents.blade.php
@extends('layouts.app')
@section('css')
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
	<link rel="stylesheet" type="text/css"
		  href="https://cdn.datatables.net/responsive/2.2.2/css/responsive.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css"
		  href="{{asset('css/tables-custom.css')}}"/>
@endsection
@section('main')


	@if ($message = Session::get('success'))
		<div class="alert alert-success">
			<p>{{ $message }}</p>
		</div>
	@endif
	@if ($message = Session::get('error'))
		<div class="alert alert-danger">
			<p>{{ $message }}</p>
		</div>
	@endif
	<h1>Eventos</h1>
	<div class="div-bg-gray ">
		<div class="card-body">
			<table id="key-table" style="width: 100%;"
				   class="table table-striped table-hover dataTable border-table border-table">
				<thead>
				<th>Evento</th>
				<th>Cliente Final</th>
				<th>Local</th>
				<th>Descrição</th>
				<th>Inicio Do Evento</th>
				<th>Fim Do Evento</th>
				<th>Estado</th>
				<th>Ação</th>
				</thead>
				<tbody>
				@foreach($events as $event)

					<tr>
						<td>
							{{$event->eventID}}
						</td>
						<td>
							{{$event->final_client}}
						</td>
						<td>
							{{$event->local}}
						</td>
						<td>
							{{$event->eventDescription}}
						</td>
						<td>
							{{$event->eventStartDate}}
						</td>
						<td>
							{{$event->eventEndDate}}
						</td>
						<td>
							@if($event->eventState === '1' || $event->eventState === 1)
								<p class="badge badge-success">Em Curso</p>
							@else
								<p class="badge badge-dark">Concluido</p>
							@endif
						</td>
						<td>
							<a href="{{route('clientevents.show',$event->eventID)}}"
							   class="btn btn-outline-success mr-2"><i
										class="far
							fa-window-restore"></i></a>
						</td>
					</tr>
				@endforeach

				</tbody>
			</table>
			@endsection
			@section('script')

				<script type="text/javascript"
						src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
				<script type="text/javascript"
						src="https://cdn.datatables.net/responsive/2.2.2/js/dataTables.responsive.min.js"></script>
				<script type="text/javascript"
						src="https://cdn.datatables.net/responsive/2.2.2/js/responsive.bootstrap4.min.js"></script>
				<script type="text/javascript"
						src="{{asset('js/sweetalert2.all.min.js')}}"></script>
				<script>
					$(document).ready(function () {
						var table = $('#key-table').DataTable({
							responsive: true, bInfo: false, bLengthChange: false,
							order: [0, 'desc'],
							stateSave: true,
							"language": {
								"sEmptyTable": "Nenhum registo encontrado",
								"sProcessing": "A processar...",
								"sLengthMenu": "Mostrar _MENU_ registos",
								"sZeroRecords": "Não foram encontrados resultados",
								"sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registos",
								"sInfoEmpty": "Mostrando de 0 até 0 de 0 registos",
								"sInfoFiltered": "(filtrado de _MAX_ registos no total)",
								"sInfoPostFix": "",
								"sSearch": "Procurar:",
								"sUrl": "",
								"oPaginate": {
									"sFirst": "Primeiro",
									"sPrevious": "Anterior",
									"sNext": "Seguinte",
									"sLast": "Último"
								},
								"oAria": {
									"sSortAscending": ": Ordenar colunas de forma ascendente",
									"sSortDescending": ": Ordenar colunas de forma descendente"
								}
							}
						});

					});

					function deleteEvent(id) {
						swal({
							title: 'Confirmação?',
							text: "Tem a certeza de que pretende eliminar este Evento?",
							type: 'warning',
							showCancelButton: true,
							confirmButtonColor: '#3085d6',
							cancelButtonColor: '#d33',
							confirmButtonText: 'Sim, Apagar Evento'
						}).then((result) => {
							if (result.value) {
								$.post("{{route('client.delete.event')}}", {id: id, _token: "{{csrf_token()}}"});
								swal(
										'Apagado!',
										'O Evento Foi Apagado.',
										'success',
								).then(() => {
									location.reload();
								})
							}
						})
					}

					function showModal(id) {
						const inputs = document.getElementsByTagName('input');
						for (let i = 0; i < inputs.length; i++) {
							inputs[i].disabled = true;
						}
						$('#' + id).modal('show');

					}

					function toogleState(id) {
						swal({
							title: 'Confirmação?',
							text: "Tem a certeza de que pretende mudar o estado deste Evento?",
							type: 'warning',
							showCancelButton: true,
							confirmButtonColor: '#3085d6',
							cancelButtonColor: '#d33',
							confirmButtonText: 'Sim, Mudar Estado'
						}).then((result) => {
							if (result.value) {
								$.post("{{route('client.event.state')}}", {id: id, _token: "{{csrf_token()}}"});

								swal(
										'Mudado!',
										'Estado Mudado Com Sucesso.',
										'success',
								).then(() => {
									location.reload();
								})
							}
						})
					}
				</script>
@endsection

resources/views/clientprofile.blade.php
@extends('layouts.app')
@section('css')
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href="https://cdn.datatables.net/responsive/2.2.2/css/responsive.bootstrap4.min.css"/>

@endsection
@section('main')
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="text-center">
				<h2>Activity</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="card-box">
				<div class="card-title">
					<h3>Purchases</h3>
				</div>
				<div class="card-body">
					<table id="key-table-1" class="table table-bordered">
						<thead>
						<th>
							Payment ID
						</th>

						<th>
							Start Date
						</th>
						<th>
							Expiration date
						</th>
						<th>
							Time Purchased (H/m)
						</th>
						<th>
							Purchase Date
						</th>
						</thead>
						<tbody>
						@foreach($paid as $payment)
							<tr>
								<td>
									{{$payment->minutes_paid_id}}
									@if($payment->expires_at < \Carbon\Carbon::today())
										<label class="badge badge-danger">Expired</label>
									@elseif($payment->active_at < \Carbon\Carbon::today())
										<label class="badge badge-success">Active</label>
									@else
										<label class="badge badge-info">Not Active</label>
									@endif
								</td>
								<td>
									{{$payment->active_at}}
								</td>
								<td>
									{{$payment->expires_at}}
								</td>
								<td>
									{{$payment->Number_of_hours_paid}}
								</td>
								<td>
									{{$payment->created_at}}
								</td>
							</tr>
						@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-lg-12 margin-tb">
			<div class="card-box">
				<div class="card-title">
					<h3>Tasks</h3>
				</div>
				<div class="card-body">
					<table id="key-table-2" class="table table-bordered">
						<thead>
						<th>
							Task ID
						</th>
						<th>
							Date
						</th>
						<th>
							Description
						</th>
						<th>
							Time Spent (H/m)
						</th>
						</thead>
						<tbody>
						@foreach($spend as $spent)
							<tr>
								<td>
									{{$spent->minutes_spent_id}}
								</td>
								<td>
									{{$spent->created_at}}
								</td>
								<td>
									{{$spent->description}}
								</td>
								<td>
									{{$spent->hours_spent}}
								</td>
							</tr>
						@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	@if ($message = Session::get('success'))
		<div class="alert alert-success">
			<p>{{ $message }}</p>
		</div>
	@endif
	@if ($message = Session::get('error'))
		<div class="alert alert-danger">
			<p>{{ $message }}</p>
		</div>
	@endif





@endsection
@section('script')

	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
	<script type="text/javascript"
	        src="https://cdn.datatables.net/responsive/2.2.2/js/dataTables.responsive.min.js"></script>
	<script type="text/javascript"
	        src="https://cdn.datatables.net/responsive/2.2.2/js/responsive.bootstrap4.min.js"></script>

	<script>
        $(document).ready(function () {
            $('#key-table-1').DataTable({
                responsive: true, bInfo: false, bLengthChange: false,
                order: [0, 'desc'],

            });
        });
	</script>
	<script>
        $(document).ready(function () {
            $('#key-table-2').DataTable({
                responsive: true, bInfo: false, bLengthChange: false,
                order: [0, 'desc'],
            });
        });
	</script>
@endsection