routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
    'as' => 'index',
    'uses' => 'IndexController@index',
]);;
Auth::routes();
Route::group(['middleware' => ['permission:worker']], function () {
    Route::resource('dashboard', 'DashBoardController');
    Route::get('/getpiedata/{id}', 'DashBoardController@getPie')->name('Data');
    Route::get('/getbardata/{id}', 'DashBoardController@getbar')->name('Data');
    Route::get('/activity', 'DashBoardController@activity')->name('Profile');
    Route::get('/workers/documents/{id}/edit', [
        'as' => 'workers.document.edit',
        'uses' => 'WorkerController@documents',
    ]);

    Route::post('/workers/permanent/delete/', [
        'as' => 'workers.delete.permanent',
        'uses' => 'WorkerController@deleteworker',
    ]);
    Route::post('/documents', [
        'as' => 'workers.document.updatedoc',
        'uses' => 'WorkerController@updatedoc',
    ]);
    Route::post('/workers/documents/download/', [
        'as' => 'workers.document.download',
        'uses' => 'WorkerDocsController@document_download',
    ]);
    Route::resource('workers', 'WorkerController');

});
Route::group(['middleware' => ['permission:administrator']], function () {
    Route::resource('client', 'ClientController');
    Route::post('client/delete', [
        'as' => 'client.delete',
        'uses' => 'ClientController@delete',
    ]);
    Route::post('client/state', [
        'as' => 'client.state',
        'uses' => 'ClientController@state',
    ]);
    Route::post('client/event/store', [
        'as' => 'client.store.event',
        'uses' => 'ClientController@storeEvent',
    ]);
    Route::get('client/{id}/create', [
        'as' => 'client.create.event',
        'uses' => 'ClientController@createEvent',
    ]);
    Route::get('client/event/{id}', [
        'as' => 'client.show.event',
        'uses' => 'ClientController@showEvent',
    ]);
    Route::post('client/event/delete', [
        'as' => 'client.delete.event',
        'uses' => 'ClientController@deleteEvent',
    ]);
    Route::post('client/event/state', [
        'as' => 'client.event.state',
        'uses' => 'ClientController@stateEvent',
    ]);
    Route::get('client/event/{id}/addworker/', [
        'as' => 'client.event.addWorker',
        'uses' => 'ClientController@addEventWorker',
    ]);

    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::get('/users/enterprise/new', [
        'as' => 'users.Enterprise',
        'uses' => 'UserController@Enterprise',
    ]);
    Route::get('/users/enterprise/change', [
        'as' => 'users.Enterprise.edit',
        'uses' => 'UserController@EnterpriseEdit',
    ]);
    Route::get('/admin/{id}/{date}/entfilter', [
        'as' => 'dashboard.company.filter',
        'uses' => 'AdminController@enterfilter',
    ]);
    Route::get('/admin/{id}/{date}/workfilter', [
        'as' => 'dashboard.worker.filter',
        'uses' => 'AdminController@workfilter',
    ]);

    Route::post('/users/enterprise', [
        'as' => 'users.store_enterprise',
        'uses' => 'UserController@PostEnterprise',
    ]);
    Route::post('/users/enterpriseedit', [
        'as' => 'users.store_enterprise_edit',
        'uses' => 'UserController@PostEnterpriseEdit',
    ]);
    Route::post('/admin-filter', [
        'as' => 'dashboard.filter',
        'uses' => 'AdminController@filter',
    ]);
    Route::resource('workers', 'WorkerController');
    Route::resource('admin', 'AdminController');
    Route::resource('otherworkers', 'OtherworkersController');
    Route::get('company/{id?}/details', [
        'as' => 'companies.info',
        'uses' => 'CompaniesController@details',
    ]);
    Route::post('company/details', [
        'as' => 'companies.info.update',
        'uses' => 'CompaniesController@detailsUpdate',
    ]);

    Route::resource('companies', 'CompaniesController');
    Route::get('company/{id?}/filter', [
        'as' => 'company.filter',
        'uses' => 'CompanyDocController@filter',
    ]);
    Route::post('/workers/documents/downloadadmin/', [
        'as' => 'workers.document.downloadadmin',
        'uses' => 'WorkerDocsController@document_download_admin',
    ]);
    Route::post('/company/delete', [
        'as' => 'company.delete',
        'uses' => 'CompanyDocController@deleteType',
    ]);
    Route::post('/company/create', [
        'as' => 'company.document.typecreate',
        'uses' => 'CompanyDocController@POST_type',
    ]);
    Route::get('/company/delete', [
        'as' => 'company.deleteview',
        'uses' => 'CompanyDocController@deleteview',
    ]);
    Route::post('/workers/type/delete', [
        'as' => 'workers.delete',
        'uses' => 'WorkerDocsController@deleteType',
    ]);
    Route::get('/workers/type/delete', [
        'as' => 'workers.deleteview',
        'uses' => 'WorkerDocsController@deleteview',
    ]);
    Route::get('/workers/documents/new', [
        'as' => 'workers.document.type',
        'uses' => 'WorkerController@newDocType',
    ]);
    Route::post('/documents/typecreate', [
        'as' => 'workers.document.POST_type',
        'uses' => 'WorkerController@POST_type',
    ]);
    Route::post('/worker/approve', [
        'as' => 'worker.document.approve',
        'uses' => 'WorkerDocsController@approve',
    ]);
    Route::post('/worker/deny', [
        'as' => 'worker.document.deny',
        'uses' => 'WorkerDocsController@deny',
    ]);
    Route::post('/worker/delete', [
        'as' => 'worker.document.delete',
        'uses' => 'WorkerDocsController@deletedoc',
    ]);
    Route::post('/company/approve', [
        'as' => 'company.document.approve',
        'uses' => 'CompanyDocController@approve',
    ]);
    Route::post('/company/deny', [
        'as' => 'company.document.deny',
        'uses' => 'CompanyDocController@deny',
    ]);
});
Route::group(['middleware' => ['permission:manager']], function () {
    Route::resource('company', 'CompanyDocController');
    Route::post('/company/getfile', [
        'as' => 'company.document.get',
        'uses' => 'CompanyDocController@POST_getFiles',
    ]);
    Route::post('/company/uploadfile', [
        'as' => 'company.document.set',
        'uses' => 'CompanyDocController@POST_upload',
    ]);
    Route::post('/event/file/download', [
        'as' => 'event.document.download',
        'uses' => 'ClientController@getDownload',
    ]);
    Route::post('/company/getDocs', [
        'as' => 'worker.document.get',
        'uses' => 'WorkerDocsController@getWorkerDocs',
    ]);
    Route::post('/client/event/worker/add', [
        'as' => 'client.event.store.worker',
        'uses' => 'ClientController@storeEventWorker',
    ]);
    Route::get('/Companyfileupload', [
        'as' => 'company.document.upload',
        'uses' => 'CompanyDocController@upload',
    ]);
    Route::get('/client/event/{id}/worker/{workerID}', [
        'as' => 'client.event.worker.show',
        'uses' => 'ClientController@showWorkerDocs',
    ]);
    Route::get('company/{id?}/filter', [
        'as' => 'company.filter',
        'uses' => 'CompanyDocController@filter',
    ]);
    Route::get('workers/{id?}/filter', [
        'as' => 'workers.filter',
        'uses' => 'WorkerDocsController@filter',
    ]);

    Route::resource('workers', 'WorkerController');

});
Route::group(['middleware' => ['permission:client']], function () {
    Route::resource('clientevents', 'ClientEventsController');
    Route::get('clientevents/{id}/{workerID}', [
        'as' => 'clientevents.worker',
        'uses' => 'ClientEventsController@worker',
    ]);
    Route::post('clientevents/filedownload', [
        'as' => 'clientevents.download',
        'uses' => 'ClientController@getDownload',
    ]);
});

app/CompanyDocs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @method static create(array $array)
 */
class CompanyDocs extends Model
{
    protected $table = 'Companydocs';

    protected $primaryKey = 'company_documentID';

    protected $fillable = [
        'documentName',
        'document_extension',
        'company_id',
        'expires_at',
        'fk_typeID',
        'documentNameOriginal',
        'valid',
        'description',
    ];

    public function enterprise()
    {
        return $this->belongsTo('App\Enterprise', 'company_id', 'enterpriseID');
    }

    public function types()
    {
        return $this->hasone('App\DocCompanyType', 'typeID', 'fk_typeID');
    }
}

app/Http/Controllers/CompanyDocController.php
<?php

namespace App\Http\Controllers;

use App\CompanyDocs;
use App\DocCompanyType;
use App\Enterprise;
use App\Mail\EmailSender;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Storage;
use stdClass;

class CompanyDocController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return array
     */
    public function index()
    {
        $filter = 0;

        $user = auth()
            ->user();

        $files = CompanyDocs::all();

        return view('companydocs.index')
            ->with('docs', $files)
            ->with('user', $user)
            ->with('filter', $filter);
    }

    /**
     * @param $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function filter($id)
    {
        $filter = 1;

        $user = auth()
            ->user();

        $enterprise = Enterprise::find($id);

        $files = CompanyDocs::all()
            ->where('company_id', '=', $id);

        return view('companydocs.index')
            ->with('docs', $files)
            ->with('user', $user)
            ->with('enterprise', $enterprise)
            ->with('filter', $filter);
    }

    public function deleteview()
    {
        $types = DocCompanyType::All();

        return view('companydocs.delete')
            ->with('types', $types);
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = auth()
            ->user();

        return view('companydocs.create')
            ->with('user', $user);
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function upload()
    {
        $user = auth()
            ->user();

        $enterprise = Enterprise::all();

        $types = DocCompanyType::all();

        return view('companydocs.upload')
            ->with('user', $user)
            ->with('types', $types)
            ->with('enterprise', $enterprise);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */

    public function POST_type(Request $request)
    {
        $expires = FALSE;

        if ($request['expires'] == 'on') {
            $expires = TRUE;
        }

        DocCompanyType::create(
            ['typeName' => $request['name'], 'expires' => $expires,]
        );

        return redirect()
            ->route('company.index')
            ->with('success', 'Tipo De Ficheiro Adicionado Com Sucesso');
    }

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Symfony\Component\HttpFoundation\StreamedResponse
     */
    public function POST_getFiles(Request $request)
    {
        $attributes = explode('.', $request['doc']);

        $doc = CompanyDocs::all()
            ->where('documentName', '=', $attributes['0'])
            ->first();

        $file = Storage::download('/documents/company/' . $request['id'] . '/' . $request['doc'], preg_replace('/[[:^print:]]/', '', $doc['documentNameOriginal']));

        $strorage = Storage::disk('local')
            ->getAdapter()
            ->applyPathPrefix('/documents/company/' . $request['id'] . '/' . $request['doc']);

        if ($attributes['1'] === 'pdf') {
            return Response::make(file_get_contents($strorage), 200, [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; filename="' . preg_replace('/[[:^print:]]/', '', $doc['documentNameOriginal']) . '"',
            ]);
        } else {
            return $file;
        }
    }

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function POST_upload(Request $request)
    {
        $this->validate($request, [
            'doc' => 'mimes:pdf',
            'id' => 'required',
        ]);

        $doc = $request->file('doc');

        $original = $doc->getClientOriginalName();

        $original = explode('.', $original);

        $originalName = $original['0'];

        $originalExtension = $original['1'];

        $type = explode('/', $request['typename']);

        $count = CompanyDocs::all()
            ->where('company_id', '=', $request['id'])
            ->where('fk_typeID', '=', $type['0'])
            ->count();

        if ($count > 0) {

            $file = CompanyDocs::all()
                ->where('company_id', '=', $request['id'])
                ->where('fk_typeID', '=', $type['0'])
                ->first();

            CompanyDocs::destroy($file['company_documentID']);

            Storage::delete('/documents/company/' . $request['id'] . '/' . $file['documentName'] . '.' . $file['document_extension']);
        }
        $hash = uniqid() . File::extension($originalName);

        $url = $doc->storePubliclyAS('/documents/company/' . $request['id'] . '', '' . $hash . '.' .
            $originalExtension);


        $expire = $request['expire_date'];

        CompanyDocs::create([
            'documentName' => $hash,
            'documentNameOriginal' => $originalName,
            'document_extension' => $originalExtension,
            'company_id' => $request['id'],
            'expires_at' => $expire,
            'fk_typeID' => $type['0'],
        ]);
        $data = new stdClass();
        $data->link = route('company.filter', ['id' => $request['id']]);
        $data->what = 'Ficheiro de Entidade Adicionado';
        $to = 'diogo.adao@visual-thinking.pt';
        Mail::to($to)->send(new EmailSender($data));

        return redirect()
            ->route('company.index')
            ->with('success', 'Ficheiro Adicionado');
    }

    public function approve(Request $request)
    {
        $doc = CompanyDocs::all()
            ->where('documentName', '=', $request['doc'])
            ->first();

        $doc->valid = '1';

        $doc->save();

        return redirect()
            ->back()
            ->with('success', 'Aprovado Com Sucesso');
    }

    public function deny(Request $request)
    {
        $doc = CompanyDocs::all()
            ->where('documentName', '=', $request['doc'])
            ->first();

        $doc->valid = '2';

        $doc->save();

        $doc->description = $request['desc'];

        $doc->save();

        return redirect()
            ->back()
            ->with('success', 'Rejeitado Com Sucesso');
    }

    public function deleteType(Request $request)
    {
        DocCompanyType::destroy($request['typename']);

        return redirect()
            ->route('company.index')
            ->with('success', 'Tipo De Documento Apagado com Sucesso');
    }


}

resources/views/companydocs/index.blade.php
@extends('layouts.app')
@section('css')
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href="https://cdn.datatables.net/responsive/2.2.2/css/responsive.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css"
	      href="{{asset('css/tables-custom.css')}}"/>
@endsection
@section('main')
	<style>
		.border300 {
			border-radius: 300px;
		!important;
			padding: 0;
		!important;
			margin: 0 0 0;
		!important;

		}

		.fa25 {
			font-size: 25px;
		!important;
		}
	</style>
	<div class="row">
		<div class="col-lg-12 margin-tb">
			<div class="pull-left">
				@if($filter == 1)
					<h2>{{$enterprise->enterpriseName}}</h2>
				@else
					<h2>Documentos</h2>
				@endif
			</div>
			@if($filter == 1)
				<div class="col-lg-12 margin-tb">
					<div class="pull-right pd5-all ">
						<a class="btn btn-primary" href="{{ route('admin.index') }}"> Voltar</a>
					</div>
				</div>
			@endif
			<div class="pull-right pd5-all">
				<a title="Submeter" class="btn btn-success " href="{{ route('company.document.upload') }}"><i
							class="fas fa-file-upload fa-1x"></i></a>
			</div>
			@can('manager')
				@if(Auth::user()->enterprise->enterpriseID ==1)
					<div class="col-lg-12 margin-tb">
						<div class="pull-right pd5-all">
							<a title="Adicionar" class="btn btn-success" href="{{ route('company.create') }}"><i
										class="far fa-plus-square fa-1x"></i></a>
						</div>
					</div>
					<div class="col-lg-12 margin-tb">
						<div class="pull-right pd5-all">
							<a title="Remover" class="btn btn-success" href="{{ route('company.deleteview')}}"><i
										class="far fa-minus-square fa-1x"></i></a>
						</div>
					</div>
					@if($filter == 0)
						<div class="col-lg-12 margin-tb">
							<div class="pull-right pd5-all">
								<a id="all" name="all" value="{{$user->enterprise->enterpriseName}}"
								   class="btn btn-success">Todos</a>
							</div>
						</div>
						<div class="col-lg-12 margin-tb">
							<div class="pull-right pd5-all">
								<a id="mine" name="mine" value="{{$user->enterprise->enterpriseName}}"
								   class="btn btn-success">Interno</a>
							</div>
						</div>

					@endif
				@endif
			@endcan
		</div>
	</div>

	@if ($message = Session::get('success'))
		<div class="alert alert-success">
			<p>{{ $message }}</p>
		</div>
	@endif
	@if ($message = Session::get('error'))
		<div class="alert alert-danger">
			<p>{{ $message }}</p>
		</div>
	@endif
	<div class="div-bg-gray ">
		<div class="card-body">
			<table id="key-table" style="width: 100%;"
			       class="table table-striped table-hover dataTable border-table">
				<thead>
				@if($filter != 1)
					<th>ENTIDADE</th>
				@endif
				<th>DOCUMENTO</th>
				<th>ESTADO</th>
				<th>VALIDADE</th>
				@can('administrator')
					<th>AÇÃO</th>
				@endcan

				</thead>
				<tbody>
				@foreach($docs as $doc)
					@if($user->enterprise->enterpriseID == $doc->company_id or $user->enterprise->enterpriseID == 1)
						<tr>
							@if($filter != 1)
								<td>
									<div class="pd5-all">{{$doc->enterprise->enterpriseName}}</div>
								</td>
							@endif
							<td>
								<div class="pd5-all">
									<form method="post" action="{{route('company.document.get')}}">
										@csrf
										<input type="hidden" id="doc" name="doc"
										       value="{{$doc->documentName}}.{{$doc->document_extension}}">
										<input type="hidden" id="id" name="id" value="{{$doc->company_id}}">
										<input type="hidden" id="hash" name="hash"
										       value="@php echo(Illuminate\Support\Facades\Hash::make( \Carbon\Carbon::today() && $doc->documentName && $user->email && $user->enterprise->enterpriseName));@endphp">
										<button class="btn"
										        style="padding-top: 3px;padding-bottom: 3px;">@if($doc->document_extension == 'pdf')
												<i class="far fa-file-pdf"></i>&ensp;{{$doc->types->typeName}}
											@elseif($doc->document_extension == 'docx')
												<i class="far fa-file-word"></i>
												&ensp;{{$doc->types->typeName}}
											@elseif($doc->document_extension == 'docx')
												<i class="far far fa-file-excel"></i>
												&ensp;{{$doc->types->typeName}}
											@else
												<i class="far far fa-file"></i>
												&ensp;{{$doc->types->typeName}}

											@endif</button>
									</form>
								</div>
							</td>
							<td>
								<div class="pd5-all">
									@php
										$valid= $doc->valid;
										$expires_at = $doc->expires_at;

									if($valid == 2) {
									echo('<label data-toggle="tooltip" title="'.$doc->description .'" class="badge badge-danger  text-16"><i class="fas fa-times-circle fa-1x"></i></label>');
									 }else if($expires_at < Carbon\Carbon::today('Europe/Lisbon') && $expires_at != NULL ){
								   echo('<label data-toggle="tooltip" title="Documento Expirado" class="badge badge-danger  text-16"><i class="fas fa-times-circle fa-1x"></i></label>');
									   }
									else if($valid == 0)
									{
									echo('<label class="badge badge-warning  text-16"><i class="fas fa-exclamation-circle fa-1x"></i></label>');
									   }else if ($valid ==1 && $expires_at === NULL ){
						   echo('<label class="badge badge-success pd5-all text-16"><i class="fas fa-check fa-1x"></i></label>');
						   }else{
						   echo('<label class="badge badge-warning pd5-all text-16"><i class="fas fa-check
						   fa-1x"></i></label>');
						   }

									@endphp
								</div>

							</td>
							<td>
								<div class="pd5-all">

									@php
										$expire= $doc->expires_at;

									iF($expire == NULL)
									{
									 echo('<label class="badge"><i class="fas fa-ban fa-2x"></i></label>');
									}else if($expire < Carbon\Carbon::today('Europe/Lisbon') && $expires_at != NULL){
									echo('<label class="badge text-16">'.$expire.'</label>');
									}else if($expire < Carbon\Carbon::today('Europe/Lisbon')->addMonth(1) && $expires_at != NULL){
									echo('<label class="badge text-16">'.$expire.'</label>');
									}
									else{
									echo('<label class="badge text-16">'.$expire.'</label>');
									}
									@endphp
								</div>

							</td>
							@can('administrator')
								<td>
									<div class="row">

										@if(Auth::user()->enterprise->enterpriseID ==1)
											<div class="pd5-all">
												<form method="post" action="{{route('company.document.approve')}}">
													@csrf
													<input type="hidden" id="doc" name="doc"
													       value="{{$doc->documentName}}">
													<button style="padding-top: 3px;padding-bottom: 3px;"
													        class="btn btn-success"><i
																class="far fa-thumbs-up fa-1x"></i>
													</button>
												</form>
											</div>
											<div class="pd5-all">
												<form id="deny{{$doc->documentName}}.{{$doc->document_extension}}"
												      method="post"
												      action="{{route('company.document.deny')}}">
													@csrf
													<input type="hidden" id="doc" name="doc"
													       value="{{$doc->documentName}}">

												</form>
												<button style="padding-top: 3px;padding-bottom: 3px;"
												        class="btn btn-danger"
												        onclick="deny('deny{{$doc->documentName}}.{{$doc->document_extension}}');">
													<i class="far fa-thumbs-down fa-1x"></i>
												</button>
											</div>
											<div class="pd5-all">
												<input type="hidden"
												       id="reason_deny{{$doc->documentName}}.{{$doc->document_extension}}"
												       placeholder="Motivo de Rejeição"
												       form="deny{{$doc->documentName}}.{{$doc->document_extension}}"
												       class="form-control" type="text" id="desc" name="desc">
											</div>
										@endif
									</div>
								</td>
							@endcan
						</tr>
					@endif
				@endforeach
				</tbody>
			</table>

			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="pull-left">
						<h4>Legenda</h4>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-2">
					<div>
						<strong>
							<a class="border300 btn btn-success"><i class="fa25 fas fa-check fa-1x"></i></a>&nbsp;Válido
						</strong>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-2">
					<div>
						<strong>
							<a class="border300 btn btn-warning"><i class="fa25 fas fa-check fa-1x"></i></a>&nbsp;
							Validade Reduzida
						</strong>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-2">
					<div>
						<strong>
							<a class="border300 btn btn-warning"><i class="fa25 fas
							fa-exclamation-circle"></i></a>&nbsp;Pendente
						</strong>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-2">
					<div>
						<strong>
							<a class="border300 btn btn-danger"><i class="fa25 fas fa-times-circle"></i></a>&nbsp;Inválido
						</strong>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-2">
					<div>
						<strong>
							<a class="border300 btn btn-info"><i class="fa25 fas fa-plus-circle"></i></a>&nbsp;Vazio
						</strong>
					</div>
				</div>
			</div>
		</div>
	</div>


@endsection
@section('script')

	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
	<script type="text/javascript"
	        src="https://cdn.datatables.net/responsive/2.2.2/js/dataTables.responsive.min.js"></script>
	<script type="text/javascript"
	        src="https://cdn.datatables.net/responsive/2.2.2/js/responsive.bootstrap4.min.js"></script>
	<script type="text/javascript" src="{{asset('js/sweetalert2.all.min.js')}}"></script>
	<script>
        $(document).ready(function () {
            const table = $('#key-table').DataTable({
                responsive: true,
                bInfo: false,
                bLengthChange: false,
                order: [0, 'desc'],
                stateSave: true,
                "language": {
                    "sEmptyTable": "Nenhum registo encontrado",
                    "sProcessing": "A processar...",
                    "sLengthMenu": "Mostrar _MENU_ registos",
                    "sZeroRecords": "Não foram encontrados resultados",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registos",
                    "sInfoEmpty": "Mostrando de 0 até 0 de 0 registos",
                    "sInfoFiltered": "(filtrado de _MAX_ registos no total)",
                    "sInfoPostFix": "",
                    "sSearch": "Procurar:",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "Primeiro",
                        "sPrevious": "Anterior",
                        "sNext": "Seguinte",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
            $("#all").click(function () {
                table.search("").draw();
            });
            $("#mine").click(function () {
                table.search("{{$user->enterprise->enterpriseName}}").draw();
            });
        });


	</script>
	<script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        function deny(id) {
            (async function getText() {
                const {value: text} = await swal({
                    input: 'textarea',
                    title: 'Motivo',
                    inputPlaceholder: 'Motivo de rejeição',
                    showCancelButton: true
                });

                if (text) {

                    var element = document.getElementById('reason_' + id);
                    element.value = text;

                    document.getElementById(id).submit();
                }

            })()
        }
	</script>

@endsection